baseURL: 'https://chloezhang21.netlify.app'
languageCode: 'en-us'
title: 'Chloe Zhang'
theme: hugo-profile

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  page:
    - 'HTML'
    - 'RSS'

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
  #Dropdown menu
  # - identifier: dropdown
  #   title: Example dropdown menu
  #   name: Dropdown
  #   weight: 3
  # - identifier: dropdown1
  #   title: example dropdown 1
  #   name: example 1
  #   url: /#
  #   parent: dropdown
  #   weight: 1
  # - identifier: dropdown2
  #   title: example dropdown 2
  #   name: example 2
  #   url: /#
  #   parent: dropdown
  #   weight: 2

params:
  title: 'Chloe Zhang'
  description: Text about my cool site
  # staticPath: "/resources/_gen/images"  # The path to serve the static files from
  favicon: '/logo.png'

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: '/logo.png' # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: 'Chloe Zhang' # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: true
      disableProjects: true
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: 'Chloe.'
    subtitle: 'Building websites that engage and inspire'
    content: 'Hello and welcome to my personal website! I am a full-stack developer with over 5 years of experience in crafting stunning web experiences.'
    image: '/images/hero.svg'
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: 'Resume'
      url: 'https://drive.google.com/file/d/1xGvO5yjeYtdNDlf0I_urmHWHVQB2S-d4/view?usp=sharing'
      download: false
      newPage: true
    # socialLinks:
    #   fontAwesomeIcons:
    #     - icon: fab fa-github
    #       url: https://example.com
    #     - icon: fab fa-twitter
    #       url: https://example.com
    #   customIcons:
    #     - icon: /fav.png
    #       url: 'https://example.com'

  # About
  about:
    enable: true
    title: 'About Me'
    image: '/images/me.png'
    content: |-
      • Experienced full-stack software engineer with 5 years of experience designing and implementing front-end and back- end web applications, utilizing HTML5, CSS3, SCSS, JavaScript, TypeScript, and popular frameworks such as Angular, React.  
      •	Skilled in modules, services, authentication, directives, pipes and reactive forms in Angular.  
      •	Proficient in using RxJS for features like observables, operators, subjects, multicasting, error handling, and async/await.  
      •	Competent in designing and implementing RESTful and GraphQL APIs, including defining API schemas and data models, implementing data validation and authentication.  
      •	Experienced in building scalable and modular back-end systems with Java and Node.js.  
      •	Familiar with designing and implementing both relational databases, such as MySQL and PostgreSQL, and NoSQL database, such as MongoDB.  
      •	Possessed expertise in using design patterns such as MVC and MVVM.  
      •	Knowledgeable in utilizing NgRx for managing the state of Angular applications.  
      •	Experienced in version control tools such as Git/Github, Agile methodologies such as Scrum, and project management tools as JIRA.  
      •	Strong problem-solving, communication, organization, and planning skills, with a track record of delivering high-quality software projects on time and within budget.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - 'HTML'
        - 'CSS'
        - 'JavaScript'
        - 'React'
        - 'Node'
        - 'Express'

  # Experience
  experience:
    enable: true
    title: 'Work Experience'
    items:
      - job: 'Project: Enterprise Console'
        company: 'Big Lots Corporate'
        companyUrl: 'https://www.biglots.com/corporate/'
        date: 'Oct 2021 - Present'
        featuredLink:
          enable: false
          name: 'View the project'
          url: 'https://example.com'
        content: |-
          The enterprise console is a software application that enables Big Lots Corporate to manage its delivery operations more efficiently. The console includes a range of features that allow the company to track and manage delivery orders from start to finish. The console provides a user-friendly interface for creating and managing delivery orders, including the ability to schedule deliveries, assign drivers and vehicles, and track delivery progress in real-time. The enterprise console can improve customer satisfaction by providing accurate and timely delivery updates.

          -	Designed an intuitive interface for creating, scheduling, and managing delivery orders using Angular 13, leading to increased customer satisfaction and prompt delivery updates.  
          -	Created forms utilizing controllers, data binding, filters, and expression modules for seamless user interaction.  
          -	Designed modern and visually appealing web page layouts and styles using SCSS to enrich the user interface.  
          -	Implemented navigation between application components using the Angular router module for streamlined user experience.  
          -	Integrated NgRx for effective state management throughout the application.  
          -	Worked with MongoDB for data persistence and utilized Node.js libraries such as Mongoose for seamless interaction with the database.  
          -	Utilized Git for version control, merging, and branching to ensure efficient collaboration within the development team.  
          -	Ensured code quality and functionality by writing unit tests using Jasmine and Karma, maintaining a high standard of test coverage and reliability for the platform.  
          -	Participated in Agile methodology meetings, including daily stand-ups, sprint planning, and retrospectives, to collaborate with team members and monitor project progress.  
          -	Demonstrated strong communication and teamwork skills by effectively collaborating with team members and stakeholders to gather requirements and provide timely updates.

      - job: 'Project: Infrastructure Monitoring Dashboard'
        company: 'Nationwide Mutual Insurance Company'
        companyUrl: 'https://www.nationwide.com/'
        date: 'Sep 2019 - Sep 2021'
        featuredLink:
          enable: false
          url: 'https://example.com'
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Infrastructure Monitoring Dashboard is a platform that enables real-time monitoring of the performance and health of systems, hardware, containers, and applications for the Nationwide Mutual Insurance Company. This platform can collect thousands of metrics. Some of the features of this platform include providing users with detailed and up-to-date information on system activity and health, making it easier to detect and troubleshoot issues.

          - Developed and enhanced features using Angular 8-11, Node.js, resulting in improved application performance and functionality.
          - Crafted scalable CSS templates to enhance user experience and maintain design consistency.
          - Utilized Angular’s controllers, custom pipes, services, and custom directives for streamlined application development.
          - Leveraged ngx-chart to display performance and health data using timelines, line charts, and pie charts for easy data visualization.	
          - Created server-side functionality with Java and designed a robust relational database using MySQL for storing and managing user and metric data.
          - Implemented server-side authentication using JWT and session-based authentication, improving application security and user privacy.
          - Utilized Git for version control, code collaboration, and seamless integration of new features and bug fixes.
          - Conducted unit testing using Jasmine and Karma to ensure code quality and functionality.

      - job: 'Project: Operation Workbench'
        company: 'Alibaba Group'
        companyUrl: 'https://www.alibabagroup.com/en-US/'
        date: 'Jul 2017 - Jul 2019'
        info:
          enable: false
        featuredLink:
          enable: false
          url: 'https://example.com'
        content: |
          Operation Workbench is a tool designed to help Taobao e-commerce businesses manage their advertising campaigns and sales promotions across multiple channels. The platform allows users to create, launch, and track campaigns on multiple categories and apps from a centralized dashboard. The platform provides features to help businesses optimize their advertising ROI (Return on Investment) and increase their sales, including advanced targeting options, real-time analytics, and A/B testing. Users can also automate their sales promotions and discounts and adjust their campaigns based on performance data to maximize their results.

          - Developed user-friendly UI components such as menus, navigation bars, search boxes, and detailed lists for advertisements and discount promotions using Material UI, boosting platform usability and efficiency.
          - Incorporated dynamic routing in a single page React application utilizing React Router for improved navigation.
          - Utilized Redux for efficient state management and route parameter storage across components.
          - Employed React components and hooks to create new project features and enable more efficient logic reuse.
          - Integrated Redux with React for effective state maintenance across the application.
          - Developed server-side functionality using Node.js and Express, leveraging the GraphQL API to ensure seamless data retrieval and updates for the platform.
          - Maintained exceptional code quality and performance by developing unit tests with React Testing Library and Cypress, upholding strict criteria for test coverage and dependability across the platform.

      # - job: 'UI/UX Designer'
      #   company: 'Netflix'
      #   companyUrl: 'https://example.com'
      #   date: 'June 2017 - Nov 2019'
      #   featuredLink:
      #     enable: true
      #     url: 'https://example.com'
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: 'Product Designer'
      #   company: 'Google'
      #   companyUrl: 'https://example.com'
      #   date: 'Feb 2016 - Mar 2017'
      #   content: 'I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.'

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: 'Master of Business Administration'
        school:
          name: 'University of California, Berkeley'
          url: 'https://example.org'
        date: '2013 - 2015'
        GPA: '3.8 out of 5.0'
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: 'Bachelor of Science in Computer Science'
        school:
          name: 'Massachusetts Institute of Technology'
          url: 'https://example.org'
        date: '2009 - 2013'
        GPA: '3.9 out of 5.0'
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: 'My academic record'
          url: 'https://example.com'
      - title: 'High School'
        school:
          name: 'Thomas Jefferson High School for Science and Technology.'
          url: 'https://example.org'
        GPA: '4.2 out of 5.0'
        featuredLink:
          enable: true
          url: 'https://example.com'

  # Achievements
  achievements:
    enable: true
    title: 'Technical Skills'
    items:
      - title: Coding Languages
        content: JavaScript, TypeScript, Java, Python
      - title: UI Development
        content: HTML5, CSS3, SCSS, Bootstrap, Angular Material, jQuery, Redux
      - title: Web Tech Stack
        content: Angular, Node.js, Express.js, NestJS, React, Vue
      - title: Databases
        content: MongoDB, MySQL, PostgreSQL, GraphQL
      - title: Development Methodologies
        content: Agile/Scrum, Waterfall
      - title: Testing & Debugging Tools
        content: Jasmine, Karma, Cypress, Junit, Postman
      - title: Version Control & Project Management
        content: Git/Github, Jira
      - title: IDE
        content: VS Code, IntelliJ, Eclipse, Visual Studio

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - 'Hugo'
          - 'Bootstrap'
          - 'Javascript'
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - 'Django'
          - 'Bootstrap'
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - 'Hugo'
          - 'Bootstrap'
          - 'Javascript'
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: |-
      Phone: 216-674-6740   
      Email: cholezhang21@gmail.com  
      Personal Website: https://chloezhang21.netlify.app/

    email: cholezhang21@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: 'blogs'
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: 'min read'
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: 'Read'
    toc: 'Table Of Contents'
    copyright: 'All rights reserved'
    pageNotFound: 'Page not found'
    emailText: 'Check out this site'

  datesFormat:
    article: 'Jan 2, 2006'
    articleList: 'Jan 2, 2006'
    articleRecent: 'Jan 2, 2006'
